import { Router } from "express";
import {ngoLogin, ngoRegister,forgetPassResCheckUser,forgetPassUpdatePassNgo,changePassNgo,deleteProfile} from "../controller/ngoController";
import {restRequestNgo,userRequestNgo,myRequestNgo,viewNgoStats,viewNgoProfile,viewDonation,viewUserDonation,viewRestDonation,editProfileNgo,acceptDonation, findNgoUser, findNgoRest} from "../controller/ngoController";
import multer from "multer";
import {isAuthenticatedUser} from "../middleware/auth";
const router = Router();
const upload = multer();

router.route("/login").post(ngoLogin);
// router.route("/ngoRegister").post(ngoRegister);
router.post("/register",upload.single("verifyDoc"),ngoRegister);
router.route("/changePass").post(isAuthenticatedUser,changePassNgo);
router.route("/forgetPassV").post(isAuthenticatedUser,forgetPassResCheckUser);
router.route("/forgerPassU").post(isAuthenticatedUser,forgetPassUpdatePassNgo);
router.route("/deleteProfile").post(isAuthenticatedUser,deleteProfile);
router.route("/viewStats").post(isAuthenticatedUser,viewNgoStats);
router.route("/viewProfile").post(isAuthenticatedUser,viewNgoProfile);
router.route("/viewDonation").post(isAuthenticatedUser,viewDonation);
router.route("/viewUserDonation").post(isAuthenticatedUser,viewUserDonation);
router.route("/viewRestDonation").post(isAuthenticatedUser,viewRestDonation);
router.route("/editProfileNgo").post(isAuthenticatedUser,editProfileNgo);
router.route("/acceptDonation").post(isAuthenticatedUser,acceptDonation);
router.route("/myRequest").post(isAuthenticatedUser,myRequestNgo);
router.route("/myRequest/user").post(isAuthenticatedUser,userRequestNgo);
router.route("/myRequest/rest").post(isAuthenticatedUser,restRequestNgo);
router.route("/findNgoUser").post(isAuthenticatedUser,findNgoUser);
router.route("/findNgoRest").post(isAuthenticatedUser,findNgoRest);
// router.route("/test").post(test);
export default router;